version: "3.8"
services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
            args:
                REACT_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        volumes:
            # For development, we might still want to mount the source code
            # But be aware this won't reflect in the Nginx served files without a rebuild
            - ./frontend:/app
            - /app/node_modules
            - /app/build # Prevent local build from overwriting container build
        ports:
            - "3001:80" # Map host 3001 to container Nginx port 80
        # Remove environment variables related to react-scripts start
        # environment:
        #     - CHOKIDAR_USEPOLLING=true
        #     - WATCHPACK_POLLING=true
        #     - WDS_SOCKET_PORT=3500
        #     - APP_ENV=${APP_ENV:-dev}
        # Remove command, rely on Dockerfile CMD
        # command: npm start

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            # Keep volume for development, but it won't be in production image
            - ./backend:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        env_file:
            - ./backend/.env.${APP_ENV:-dev}
        environment:
            - APP_ENV=${APP_ENV:-dev}
        restart: unless-stopped

    db:
        image: postgres:alpine
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ai_secretary${APP_ENV:-dev}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
            - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=False
            - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    postgres_data:
    pgadmin_data:
