"""added calendar booking link column

Revision ID: 0ad503581dd8
Revises: eb633aed67c1
Create Date: 2025-03-29 22:44:07.041712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ad503581dd8'
down_revision: Union[str, None] = 'eb633aed67c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calendar_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calendar_url')
    # ### end Alembic commands ###
